<?php
$content = "";
$content = <<<EOD
<p>Clicke here to sign up to our terms and conditions</p>
<p>(Effective & Last Modified November 16th, 2009)</p>
<p>Please read the following Terms of Use carefully before using this website or other services that we provide. By accessing or using our website or our services (other than to read this for the first time), you agree to these Terms of Use.</p>
<p>These Terms of Use (also sometimes referred to as the "User Agreement"), together with our Privacy Policy and any additional terms which might apply to certain products or services, govern your use of any of our websites, and your use of any other services we provide, including our surveys, reviews, newsletters, panels, communities or other services (collectively, our "Service"). Our websites include and all other websites on which we place these Terms of Use (collectively, our "Site").</p>
<p>We may from time to time modify or change the Terms of Use (see Section 17). Any revised version of the Terms of Use will be posted on our Site and the revised Terms of Use will govern your future use of our Site and Service, so you should return to our Site periodically to review these Terms of Use. If you do not agree to the revised version, you must immediately stop using our Site and Service.</p>
<p>Our Services include, among other things, delivering search results for products and services offered by third-party Merchants. We are NOT a party to any transaction you may enter with Merchants. If you have any questions, concerns or claims regarding a product or service you purchased by initiating a search using our Services, please address these to the relevant Merchant.</p>
<h5>1. INTELLECTUAL PROPERTY</h5>
<p>Our Site, Service and related content (and any derivative works or enhancements of the same) including, but not limited to, all text, illustrations, files, images, software, scripts, graphics, photos, sounds, music, videos, information, content, materials, products, services, URLs, technology, documentation and interactive features (collectively, "Site Content") and all intellectual property rights to the same are owned by us, our licensors, or both. Additionally, all trademarks, service marks, trade names and trade dress that may appear on our Site or Service are owned by us, our licensors, or both. Except for the limited use rights granted in these Terms of Use, you shall not acquire any right, title or interest in our Site or Service. Any rights not expressly granted in these Terms of Use are expressly reserved. </p>
<h5>2. ACCESS OR USING OUR SERVICE</h5>
<p>(a) To access or use some content or features of our Site or Service, you may choose to provide us certain information, we may require you to provide certain information, or require that you establish an account with us through registration. Your access to certain content or features may be limited if you are not 18 years of age or older, or the legal age in your jurisdiction to form a legally binding agreement, or for other reasons.</p>
<p>(b) Whenever you submit information to us, you agree to provide true, accurate and complete information and agree to, if the option is available, promptly update the information if there have been changes to the information you provided.</p>
<p>(c) Accounts. We may also impose restrictions on your ability to establish an account (e.g., age limits, restrict business entities from setting up accounts, limitations on the number of accounts, etc.). When registering an account, you may need to select a username ("ID") and password. You are responsible for keeping your ID and password, and other account information, confidential and are fully responsible for all activities that occur under your account, whether or not you authorized such activities. You agree to notify us immediately of any breach of security or unauthorized use of your account or ID and password by clicking here .</p>
<h5>3. LIMITATION, SUSPENSION OR TERMINATION</h5>
<p>(a) We may, in our sole discretion, temporarily or permanently change, limit, suspend or terminate your access to our Site or Service (including any Site Content or User Content) without prior notice. We may do so based on changes to our business practices (e.g., eliminating a Service, etc.), if you violate the letter and spirit of these Terms of Use, or for any other lawful reason. You agree that we are not liable to you or any third party for any such action.</p>
<p>(b) Any limitation, suspension or termination we impose shall not alter your obligations to us under these Terms of Use. The provisions of these Terms of Use which by their nature should survive any such action on our part shall survive including, but not limited to, the rights and licenses that you have granted to us in your User Content and provisions relating to indemnities, releases, disclaimers, limitations on liability, mandatory arbitration, no class action and all of the miscellaneous provisions in Section 17.</p>
<h5>4. ACCEPTABLE USE</h5>
<p>(a) Our Site and Service (including, without limitation, Site Content and User Content) are provided for your information and personal, non-commercial use only. When using our Site or Service, you agree to comply with these Terms of Use, and all applicable federal, state and local laws.</p>
<p>(b) Except as expressly permitted by these Terms of Use, you may not:</p>
- use our Site or Service in an unlawful or fraudulent manner or for such purposes, to collect personally identifiable information, or to impersonate other users;<br />
- modify our copyright/trademark or other proprietary rights notices, or interfere with the security-related features of our Site or Service (e.g., those that prevent or restrict copying Site Content);<br />
- use our Site or Service in any way to manipulate or distort, or undermine the integrity and accuracy of, any reviews and ratings, or take any action to interfere with, damage, disrupt any part of our Site or Service;<br />
- use our Site or Service to send, knowingly receive, upload/post, download, any material which does not comply with our content standards;<br />
- use our Site or Service to transmit or facilitate the transmission of any unsolicited or unauthorized advertising or promotional material;<br />
- use our Site or Service to transmit any data, or upload to our Site or Service any data, that contains viruses, Trojan horses, worms, time-bombs, keystroke loggers, spyware, adware or any other harmful programs or similar computer code designed to adversely affect the operation of any computer software or hardware;<br />
- decompile, reverse engineer or disassemble any portion of our Site or Service;<br />
- use any robot, spider, other automatic device or manual process to monitor or copy our web pages or the content contained our Site or Service, or use network-monitoring software to determine architecture of or extract usage data from our Site or Service; or<br />
- engage in any conduct that restricts or inhibits any other user from using or enjoying our Site or Service.<br />
<p>(c) You agree to fully cooperate with us to investigate any suspected or actual activity that is in breach of these Terms of Use.</p>
<h5>5. USER CONTENT</h5>
<p>(a) We may now or in the future permit you to post, upload, transmit through or otherwise provide through our Site or Service (collectively, "submit") messages, text, illustrations, files, images, graphics, photos, comments, sounds, music, videos, information (e.g., your name, e-mail address, etc.) and other content (collectively "User Content"). For example, any comment, rating or review of a product or a merchant that you post through our Site or Service is your User Content.</p>
<p>(b) Standards . You agree not to submit any User Content protected by copyright, trademark, patent, trade secret, moral right, or other intellectual property or proprietary right without the express permission of the owner of the respective right. You are solely liable for any damage resulting from your failure to obtain such permission or from any other harm resulting from your User Content. Furthermore, you represent and warrant that your User Content:</p>
- will be, in the context of reviews and ratings, based upon an actual shopping experience with the relevant merchant or third party, accurate (where facts are stated), reflect opinions genuinely held by you, and comply with all applicable laws;<br />
- will be truthful, non-misleading and non-deceptive;<br />
- will not contain any material which is tortious (e.g., defames or invades the privacy of any person, etc.), obscene, offensive, hateful or inflammatory;<br />
- will not promote sexually explicit material or violence, or promote discrimination based on race, sex, religion, nationality, disability, sexual orientation or age;<br />
- does not breach any legal duty you owe to a third party, such as a contractual duty or a duty of confidence;<br />
- will not be threatening, abuse or invade another's privacy, or provided with an intent to harass, upset or embarrass any other person;<br />
- will not be provided with an intent to impersonate any person, to misrepresent your identity or affiliation with any person, or to falsely give the impression that your User Content comes from someone else; or<br />
- will not advocate, promote or assist any unlawful act (e.g., criminal acts, copyright infringement, computer misuse, etc.).<br />
<p>(c) We may monitor, edit or remove any User Content for violation of the letter or spirit of these terms, or for any other lawful reason. However, we have no obligation to look for, edit or remove (except for removal of content pursuant to Section 15) any User Content for any reason including, without limitation, violation of these terms.</p>
<p>(d) Grant of Rights & Use . We do not claim ownership to your User Content. However, by submitting User Content, you automatically grant, or warrant that the owner has expressly granted, to us a worldwide, royalty-free, perpetual, irrevocable, non-exclusive, fully sublicensable and transferable right and license to use, reproduce, distribute, create derivative works based upon (e.g., translations, etc.), publicly display/perform, transmit and publish the User Content (in whole or in part) as we, in our sole discretion, deem appropriate in connection with our business and operations. Notwithstanding the foregoing, you waive any and all claims you may now or later have in any jurisdiction to so-called "moral rights" or rights of "droit moral" with respect to the User Content.</p>
- By submitting User Content, you also grant us the right, but not the obligation, to use your biographical or other information about you including, without limitation, all or some of your name, alias, nickname and geographical location (e.g., "Todd W. - Columbus, OH," "Julie A. - Wyoming," etc.), in connection with broadcast, print, online, or other use or publication of your User Content consistent with the license granted in the previous paragraph.<br />
- Without limiting the rights granted in the foregoing paragraphs, and for avoidance of doubt, we reserve the right to display advertisements in connection with your User Content, to use your User Content for advertising and promotional purposes, and provide third-parties your User Content. You acknowledge and agree that your User Content may be included on the websites and advertising networks of our distribution partners and third-party service providers (including their downstream users).<br />
<h5>6. RELIANCE ON SITE INFORMATION</h5>
<p>(a) Information available through our Site or Service is for educational, entertainment and promotional purposes only. While we make efforts to ensure that information provided by us is accurate, we do not represent or warrant that any User Content or Site Content is accurate, complete or current. In all instances, it is your responsibility to evaluate the accuracy, timeliness, completeness, or usefulness of Site Content, User Content, and other information and opinions expressed through our Site or Service. For instance, ratings and reviews may be informative to some but are not provided as a guarantee or prediction of the level of performance you may experience with the applicable product, service, merchant or other third party. You are solely responsible for any actions or decisions you take based on materials and information available through our Site and Service, and should carry out your own research and investigation as appropriate.<br />
<p>(b) If there is a dispute between you and anyone accessing our Site or Service, or you and any third party in connection with our Site or Service, you understand and agree that we are under no obligation to become involved. In such instances, you hereby release and its officers, directors, employees, parents, partners, successors, agents, affiliates, subsidiaries and their related companies from claims, demands and damages of every kind or nature arising out of, relating to or in any way connected with such dispute.</p>
<h5>7. ONLINE MERCHANTS AND THIRD PARTIES</h5>
<p>(a) Your dealings with online merchants or other third parties via our Site or Service, including third party websites accessed via links on our Site, are solely between you and that third party. As such, when you engage in a transaction with a third party or access a third party's website, you do so under their terms and policies, not ours. Complaints, questions and claims related to transactions with any third party should be directed to that third party.</p>
<p>(b) WE MAKE NO WARRANTIES REGARDING AND SHALL NOT BE LIABLE OR RESPONSIBLE TO YOU (WHETHER IN CONTRACT, TORT OR OTHERWISE) FOR YOUR USE OF, THE QUALITY OR LATE DELIVERY OF THE GOODS OR SERVICES FROM ANY THIRD PARTY OR FOR HONORING (OR TO CAUSE ANY MERCHANT TO HONOR) ANY ERRONEOUS INFORMATION REGARDING THE PRICE, DESCRIPTION AND AVAILABILITY OF, OR ANY DISCOUNTS, OFFERS, PROMOTIONS AND COUPONS RELATING TO ANY PRODUCT OR SERVICE OFFERINGS PROMOTED OR AVAILABLE THROUGH OUR SITE OR SERVICE.</p>
<h5>8. LIMITS ON OUR LIABILITY</h5>
<p>(a) UNDER NO CIRCUMSTANCES SHALL OR ITS OFFICERS, DIRECTORS, EMPLOYEES, PARENTS, PARTNERS, SUCCESSORS, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES OR THEIR RELATED COMPANIES BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL OR EXEMPLARY DAMAGES (EVEN IF HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES), ARISING OUT OF, RELATING TO, OR IN ANY WAY CONNECTED WITH OUR SITE, SERVICE OR THESE TERMS OF USE. YOUR SOLE REMEDY FOR DISSATISFACTION WITH OUR SITE OR SERVICE INCLUDING, WITHOUT LIMITATION, CONTENT IS TO STOP USING OUR SITE AND SERVICE. THIS LIMITATION SHALL ALSO APPLY WITH RESPECT TO DAMAGES INCURRED BY REASON OF SERVICES OR PRODUCTS, INFORMATION, ADVICE, INFORMATION OR ADVERTISING RECEIVED THROUGH OR IN CONNECTION WITH OUR SITE OR SERVICE OR ANY LINKS PROVIDED VIA EITHER. THESE LIMITATIONS SHALL APPLY TO THE FULLEST EXTENT PERMITTED BY LAW.</p>
<p>(b) REGARDLESS OF ANY INFORMATION YOU HAVE RECEIVED TO THE CONTRARY, IN NO EVENT SHALL OUR CUMULATIVE LIABILITY OR THAT OF OUR OFFICERS, DIRECTORS, EMPLOYEES, PARENTS, PARTNERS, SUCCESSORS, AGENTS, DISTRIBUTION PARTNERS, AFFILIATES, SUBSIDIARIES AND THEIR RELATED COMPANIES EXCEED $100. YOU AGREE THAT THIS IS A FAIR LIMITATION BASED UPON THE MANNER AND COST BY WHICH OUR SITE OR SERVICE ARE PROVIDED TO YOU, AND TAKING INTO ACCOUNT YOUR ABILITY TO USE ALTERNATIVE RESOURCES PROVIDING INFORMATION SIMILAR TO THAT OF OUR SITE OR SERVICE. FURTHERMORE, YOU AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF, RELATED TO, OR IN ANY WAY CONNECTED WITH OUR SITE, SERVICE OR THESE TERMS OF USE MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES. CAUSES OF ACTION BROUGHT OUTSIDE THIS TIME PERIOD ARE WAIVED.</p>
<p>(c) In some jurisdictions limitations of liability are not permitted and, therefore, some of the above limits may not apply in all instances.</p>
<h5>9. DISCLAIMER OF WARRANTIES</h5>
<p>(a) TO THE FULL EXTENT PERMITTED BY LAW, SERVICES AND ALL INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) INCLUDED ON OR OTHERWISE MADE AVAILABLE TO YOU THROUGH ITS SERVICES ARE PROVIDED BY ON AN "AS IS" AND "AS AVAILABLE" BASIS AND ARE NOT WARRANTED TO BE, AMONG OTHER THINGS, FREE OF COMPUTER VIRUSUS. YOU EXPRESSLY AGREE THAT YOUR USE OF OUR SITE AND SERVICE IS AT YOUR OWN RISK. MAKES NO REPRESENTATIONS OR WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE OPERATION OF ITS SITE OR THE INFORMATION, CONTENT, MATERIALS, PRODUCTS (INCLUDING SOFTWARE) OR SERVICES INCLUDED ON ITS SITE OR OTHERWISE MADE AVAILABLE TO YOU THROUGH ITS SERVICES.</p>
<p>(b) Certain state laws do not allow limitations on implied warranties. If these laws apply to you, some or all of the above disclaimers, exclusions or limitations may not apply to you, and you might have additional rights.</p>
<h5>10. INDEMNIFICATION</h5>
<p>You agree to indemnify and hold harmless and its officers, directors, employees, parents, partners, successors, agents, distribution partners, affiliates, subsidiaries and their related companies from and against any and all claims, liabilities, losses, damages, obligations, costs and expenses (including reasonable attorneys' fees and costs) arising out of or related to: (i) your access to or use of our Site or Service; (ii) your User Content; (iii) any actual or alleged violation or breach by you of these Terms of Use; (iv) any actual or alleged breach of any representation, warranty or covenant that you have made to us; or (v) your acts or omissions. You agree to cooperate fully with us in the defense of any claim that is the subject of your obligations hereunder.</p>
<h5>11. DISPUTE RESOLUTION AND MANDATORY ARBITRATION</h5>
<p>(a) We each agree to first contact each other with any disputes and provide a written description of the problem, all relevant documents/information and the proposed resolution. You agree to contact us with disputes by contacting us at the address provided in these Terms of Use. We will contact you based on the contact information you have provided us.</p>
<p>(b) If after 45 days the parties are unable to resolve any dispute raised under the previous provision, the dispute may be submitted to arbitration consistent with this Section. The parties understand that they would have had a right or opportunity to litigate disputes through a court and to have a judge or jury decide their case, but they choose to have any disputes resolved through arbitration.</p>
<p>(c) We each agree that any claim or dispute between us, and any claim by either of us against any agent, employee, successor, or assign of the other, including, to the full extent permitted by applicable law, third parties who are not signatories to this agreement, whether related to this agreement or otherwise, including past, present, and future claims and disputes, and including any dispute as to the validity or applicability of this arbitration clause, shall be resolved by binding arbitration administered by the JAMS under its rules and procedures in effect when the claim is filed. The rules and procedures and other information, including information on fees, may be obtained from JAMS' website (www.jamsadr.com) or by calling JAMS at 949-224-1810.</p>
<p>(d) We are entering into this arbitration agreement in connection with a transaction involving interstate commerce. Accordingly, this arbitration agreement and any proceedings thereunder shall be governed by the Federal Arbitration Act ("FAA"), 9 U.S.C. §§ 1-16. Any award by the arbitrator(s) may be entered as a judgment in any court having jurisdiction.</p>
<p>(e) Exception to Arbitrate. Either of us may bring qualifying claims in small claims court. Further, pursuant to Section 13 below, we each agree that any arbitration will be solely between you and Elations, not as part of a classwide claim (i.e., not brought on behalf of or together with another individual's claim). If for any reason any court or arbitrator holds that this restriction is unconscionable or unenforceable, then our agreement to arbitrate doesn't apply and the classwide dispute must be brought in court.</p>
<h5>12. GOVERNING LAW</h5>
<p>These Terms of Use shall be construed in accordance with the laws of the State of California without regard to its conflict of laws rules.</p>
<h5>13. NO CLASS ACTIONS</h5>
<p>TO THE EXTENT ALLOWED BY LAW, WE EACH WAIVE ANY RIGHT TO PURSUE DISPUTES ON A CLASSWIDE BASIS; THAT IS, TO EITHER JOIN A CLAIM WITH THE CLAIM OF ANY OTHER PERSON OR ENTITY, OR ASSERT A CLAIM IN A REPRESENTATIVE CAPACITY ON BEHALF OF ANYONE ELSE IN ANY LAWSUIT, ARBITRATION OR OTHER PROCEEDING.</p>
<h5>14. NO TRIAL BY JURY</h5>
<p>TO THE EXTENT ALLOWED BY LAW, WE EACH WAIVE ANY RIGHT TO TRIAL BY JURY IN ANY LAWSUIT, ARBITRATION OR OTHER PROCEEDING. </p>
<h5>15. COPYRIGHT INFRINGEMENT</h5>
<p>(a) In appropriate circumstances and in our sole discretion, we may remove or disable access to material on any of our websites or hosted on our systems that may be infringing the copyright of others.</p>
<p>(b) Consistent with the Digital Millennium Copyright Act ("DMCA"), will respond to a notice of alleged copyright infringement regarding any information available on our Site or through our Service. Please note that this procedure is exclusively for notifying us that copyrighted material has allegedly been infringed and matters other than informing that copyrighted material may have been infringed will not receive a response through this process.</p>
<p>(c) Pursuant to the DMCA, your infringement notification must include the following information:</p>
- An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;<br />
- A description of the copyrighted work that you claim has been infringed upon;<br />
- A description of where the material that you claim is infringing is located on the site, including a link or screenshot of the webpage containing the infringing material, if applicable;<br />
- Your address, telephone number and e-mail address;<br />
- A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent or the law;<br />
- A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.<br />
<h5>16. AMENDMENT; ADDITIONAL TERMS </h5>
<p>(a) We are constantly updating our Site and Services to provide better options and features, or for other reasons. In certain instances it may be necessary to update or modify our Terms of Use to reflect these and other changes (e.g., to reflect updates to our practices and policies). We also may, in some instances, need to provide you with operating rules or additional terms that govern your use of parts of our Site or any Service ("Additional Terms"). Accordingly, you agree that we may at any time provide you with Additional Terms, or update or modify these Terms of Use, as appropriate or necessary. To the extent any Additional Terms conflict with these Terms of Use, the Additional Terms will control.</p>
<p>(b) Modifications to these Terms of Use or any Additional Terms will be effective upon: (a) notice, either by posting on our Site or by email notification; and (b) your subsequent use of our Site or Service. It is your responsibility to review the Terms of Use and the Site from time to time for any changes or Additional Terms. Your access and continued use of our Site or Service following any modification of these Terms of Use or the provision of Additional Terms will signify your assent to and acceptance of the same. If you object to any revision to the Terms of Use or to any Additional Terms, immediately discontinue use of our Site and Service and, if applicable, terminate your account.</p>
<h5>17. OTHER TERMS</h5>
<p>(a) Where we have provided you with a translation of the English language version of these Terms of Use (including the Privacy Policy and any Additional Terms incorporated by reference), you agree that the translation is provided for your convenience only and that the English version of these Terms of Use governs your relationship with us. The English language version takes precedence if there is any contradiction between the English and translated versions.</p>
<p>(b) No waiver by either of us of any breach or default under these Terms of Use shall be deemed to be a waiver of any preceding or subsequent breach or default. The section headings used in these Terms of Use are for convenience only and shall not be given any legal import.</p>
<p>(c) Except where specifically stated otherwise (e.g., Section 11(e)), if any part of these Terms of Use are deemed unlawful or unenforceable for any reason, we both agree that only that part of the Terms of Use shall be stricken and that the remaining terms in the Terms of Use shall not be affected and shall remain in force and effect.</p>
<p>(d) You may not assign these Terms of Use or assign any rights or delegate any obligations hereunder, in whole or in part, without our prior written consent.</p>
<p>(e) These Terms of Use (including the Privacy Policy and any Additional Terms incorporated by reference) constitute the entire agreement, and supersede all previous written or oral agreements, between you and in connection with the Site and Service.</p>
EOD;
$page_template = str_replace("[META]", '<meta name="robots" content="noindex,nofollow" />', $page_template);
$page_template = str_replace("[SERVER-NAME]", $_SERVER['SERVER_NAME'], $page_template);
$page_template = str_replace("[PAGINATION]", "", $page_template);
$page_template = str_replace("[BOTTOM-ROW]", "", $page_template);
$page_template = str_replace("[CONTENT]", $content, $page_template);
$page_template = str_replace("[H-TITLE]", "<h4>Terms of Use</h4>", $page_template);
$page_template = str_replace("[TITLE]", "User Agreement - ".$_SERVER['SERVER_NAME'], $page_template);
?>